"""empty message

Revision ID: 215709035183
Revises: 4ddc09e73ed5
Create Date: 2020-08-16 16:42:57.991697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215709035183'
down_revision = '4ddc09e73ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userId', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('ticket',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('ticketId', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('ticketId'),
    sa.UniqueConstraint('ticketId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('user')
    # ### end Alembic commands ###
