"""empty message

Revision ID: 35a0a6b6ab60
Revises: 215709035183
Create Date: 2020-08-22 22:15:55.015737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a0a6b6ab60'
down_revision = '215709035183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assign_ticket',
    sa.Column('assignId', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('ticket_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticketId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('assignId'),
    sa.UniqueConstraint('assignId')
    )
    op.create_unique_constraint(None, 'ticket', ['ticketId'])
    op.create_unique_constraint(None, 'user', ['userId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'ticket', type_='unique')
    op.drop_table('assign_ticket')
    # ### end Alembic commands ###
