"""empty message

Revision ID: 97023efa067d
Revises: 35a0a6b6ab60
Create Date: 2020-08-23 11:10:36.622785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97023efa067d'
down_revision = '35a0a6b6ab60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assign_ticket', sa.Column('assigned_on', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('assign_ticket', sa.Column('status', sa.String(length=15), nullable=False))
    op.create_unique_constraint(None, 'assign_ticket', ['assignId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assign_ticket', type_='unique')
    op.drop_column('assign_ticket', 'status')
    op.drop_column('assign_ticket', 'assigned_on')
    # ### end Alembic commands ###
