"""empty message

Revision ID: d9e1c3b953a1
Revises: 97023efa067d
Create Date: 2020-08-23 15:38:21.781500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e1c3b953a1'
down_revision = '97023efa067d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assign_ticket', sa.Column('assigned_on', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('assign_ticket', sa.Column('status', sa.String(length=15), nullable=True))
    op.create_unique_constraint(None, 'assign_ticket', ['assignId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assign_ticket', type_='unique')
    op.drop_column('assign_ticket', 'status')
    op.drop_column('assign_ticket', 'assigned_on')
    # ### end Alembic commands ###
