"""empty message

Revision ID: e4267ca91318
Revises: c6959285f9c3
Create Date: 2020-08-23 16:23:46.258357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4267ca91318'
down_revision = 'c6959285f9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comment', ['commentId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='unique')
    # ### end Alembic commands ###
